### PR TITLE
Add Swiftify Objective-C to Swift online code converter and Xcode extension to the new "Converters" category

### PR DESCRIPTION
**Pull request by alex-swiftify**
Add Swiftify Objective-C to Swift online code converter and Xcode extension to the new "Converters" category.

### CODE REVIEW

**Comment by Porubay** [comment]
I don't even knew that such thing exist like converter from [Objective-C to Swift](https://www.cleveroad.com/blog/swift-vs-objective-c--what-is-the-best-language-for-ios-development-)

**Comment by alex-swiftify** [comment]
You are welcome to check out [Swiftify](https://objectivec2swift.com/).
Of course, we can't guarantee error free conversion, but we aim to save a lot of efforts otherwise required for manual conversion.
A couple of man-years have been already invested in Swiftify, and the project is under active development.
And feedback is also welcome.

**Comment by freak4pc** [comment]
There are some parts of that conversion I would never approve in a PR for production code. 
Explicit typing for every argument, forced unwrapping of return types, etc ... 

Also when moving away from Objective C you get to use some Swift stuff like Protocols, Generics, etc. that aren't "convertible" since they don't exist in Objective C. Using an automated tool takes all that control out of your hands if you don't tread carefully.

It seems to be a great tool to learn how Objective-C code could possibly look but I don't think I would trust something like this in production based on the few minutes I just played with it.

**Comment by alex-swiftify** [comment]
Well, even as a founder of Swiftify, I'll never accept a code produced by any automated converter to production without a manual review.

Generally, rewriting process consists of two phases: first simply replacing the syntax from Obj-C to Swift, then adopting new features that are introduced to Swift.

Swiftify is aimed at reducing the first half of the process.

>Explicit typing for every argument, forced unwrapping of return types, etc ...

Explicit typing going to become configurable very soon, and `??` operator will be always used instead of explicit unwrapping shortly.

>Also when moving away from Objective C you get to use some Swift stuff like Protocols, Generics, etc. that aren't "convertible" since they don't exist in Objective C.

Understandable, but I'd still argue with that:
- Protocols do exist in both [Objective-C](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithProtocols/WorkingwithProtocols.html) and [Swift](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html)
- Lightweight generics [do exist in Objective-C](https://useyourloaf.com/blog/using-objective-c-lightweight-generics/), and we are currently working hard on inferring necessary type information when converting non-generic types (i.e. `NSDictionary`) to Swift generics (i.e. `[AnyHashable: Any]`)

Of course, there are features that will likely be never supported (like most low-level C-like code).
Even there, we tend to provide the best possible output, for example - leaving some code like complex `#define` macros commented out in the output, so that it can be manually reviewed.

**Comment by freak4pc** [comment]
Objective-C protocols aren't comparable to Swift protocols IMO, and definitely not Objective-C's "Generics" with Swift's full-fledged generics system. There are things you CANNOT do in Objective C that are "basic" to do with Swift. Moving to a new language is the right time to reevaluate how to best use the language's features. This is just my personal opinion but a 1 to 1 conversion, despite it being an interesting learning tool and a great experiment, doesn't seem like could product actual production-quality code. If i'm wrong or not, that's a matter of preference for sure :)

Anyways looks like a great tool as I said! I would definitely use it to educate some people on moving from Objective-C and how their old code could "basically" look in Swift.

**Comment by alex-swiftify** [comment]
Sure, thanks again for the feedback!
Of course, I agree that writing idiomatic Swift code is generally a better approach, but there are still a lot of uses for Swiftify like:
- education (as you have mentioned);
- generation of code/library documentation in both languages;
- delivering samples for using a specific library / SDK in both languages;
- gradually moving existing projects to Swift on a per-file basis, i.e. using our Xcode extension;
etc.

Otherwise, understandable, and if you have more suggestions - I'm all yours :)

**Comment by alex-swiftify** [comment]
Just a quick update.
The following has been addressed:
>Explicit typing for every argument, forced unwrapping of return types, etc ...
https://objectivec2swift.com/#/converter/

Now `??` operator is used for unwrapping return types, and the same will be soon applied to method or function parameters too: 
Explicit typing has been removed when the type name is obvious to follow the Swift style guide from raywenderlich.com.

**Comment by hsavit1** [comment]
This is great. Nice work

**Pull request merged**
