### PR TITLE
add udacity courses

### PR DESCRIPTION
**Pull request by jarrodparkes**
note: udacity courses can be freely watched without enrolling in a Nanodegree. this is a guarantee by the company (i work for them), and we encourage anyone to check them out :) :+1:

### CODE REVIEW

**Comment by hsavit1** [comment]
@jarrodparkes Would you say that this course is more about learning iOS or about learning Swift?

**Comment by jarrodparkes** [comment]
a mixture of both. if you're looking for "purely" swift offerings, then i can update the link to be solely for Udacity's "Swift Syntax" course.

here's its description:

> This course focuses on the syntax of the Swift programming language. By the end of the course, you'll be able to apply Swift essentials to building iOS apps.

**Comment by hsavit1** [comment]
@jarrodparkes That would be much better. The purpose of this list is to focus more on the Swift Language, as now that it is open sourced it can be used outside of iOS development.

Also - much love for Udacity and all that they do

**Comment by jarrodparkes** [comment]
@hsavit1 changed the link! :+1:

**Pull request merged**
